ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "position" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "department" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatar" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "activeSessionId" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "activeSessionAt" TIMESTAMP(3);
