ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "animationSpeed" TEXT NOT NULL DEFAULT 'Balanced';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "sessionTimeout" INTEGER NOT NULL DEFAULT 15;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "forced" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "forcedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "scheduledDeletionAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deletionCancelledAt" TIMESTAMP(3);
