ALTER TABLE "UploadedSalesRecord" ADD COLUMN IF NOT EXISTS "salesmanGkPercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "UploadedSalesRecord" ADD COLUMN IF NOT EXISTS "fob" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "UploadedSalesRecord" ADD COLUMN IF NOT EXISTS "counter" TEXT;
